### ISSUE TITLE
Generating JNI code fails for classes with same name but different package/outer class

### ISSUE THREAD

**Issue by DasAmpharos** [LanderlYoung/Jenny#12]
My specific use case is for wrapping a C++ library for Java. I am defining a `private` nested `object` named `Native` within each class that contains all of my `external` functions. 

i.e.
```
class SomeClass {
  @NativeClass
  private object Native {
     external fun doSomething()
  }
}

class AnotherClass {
  @NativeClass
  private object Native {
     external fun doSomethingElse()
  }
}
```

When running the `kaptKotlin` task, the JNI code generation fails due to `java.lang.reflect.InvocationTargetException (no error message)`. Running the task with the `--info` flag shows 

```
error: Jenny failed to process javax.annotation.processing.FilerException Attempt to reopen a file for path $PROJECT_DIR/build/generated/source/kapt/main/jenny/glue/header/Native.h
```

Because Jenny is generating the JNI file names solely based on the class name annotated with `@NativeClass`, it does not allow for naming collisions in the case of inner classes or different packages (i.e. `com.example.SomeClass` vs. `com.example.apackage.SomeClass`). JNI headers generated using `javah` or `javac -h` avoid this by creating headers that include the fully qualified name of the class.

**Comment by DasAmpharos** [comment]
@LanderlYoung any thoughts on this?

**Comment by LanderlYoung** [comment]
emmm... this is a bug.

will fix it latter, or any PR is welcome~

**Comment by LanderlYoung** [comment]
try this:

```C++
class SomeClass {
  @NativeClass(namespace = "some")
  private object Native {
     external fun doSomething()
  }
}

class AnotherClass {
  @NativeClass(namespace = "another")
  private object Native {
     external fun doSomethingElse()
  }
}
```

**Comment by LanderlYoung** [comment]
Sorry for didn't see the PR early.
And also thanks for the PR~

But that PR only solves the duplicated file issue, but the two classes are still conflicted symbols in C++, maybe the namespace solution works better?

Feel free to discuss further~
