### ISSUE TITLE
Missing void ** cast

### ISSUE THREAD

**Issue by umarti** [LanderlYoung/Jenny#15]
File https://github.com/LanderlYoung/Jenny/blob/master/cpp/jnihelper.h has a missing cast,  clang complains on line 596:
from:
`_jvm->AttachCurrentThread(&env, nullptr);`
to:
`_jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);`

An import leads to compile errors (method not found) using clang/linux on line 23, I can't verify it on Android.
from:
`#include <string>`
to
`#include <cstring>`

Patch:

```
--- jnihelper.h	2023-11-29 07:55:21
+++ new.h	2023-11-29 07:56:09
@@ -20,7 +20,7 @@
 #include <jni.h>
 #include <cassert>
 #include <memory>
-#include <string>
+#include <cstring>
 
 #ifdef __ANDROID__
 #include <pthread.h>
@@ -593,7 +593,7 @@
       JNIEnv* env;
 
       explicit EnvWrapper(JavaVM* _jvm) : jvm(_jvm), env(nullptr) {
-        _jvm->AttachCurrentThread(&env, nullptr);
+        _jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);
         assert(env != nullptr);
       }


```

**Comment by LanderlYoung** [comment]
Thanks for the issue, turns out Android's `jni.h` is slightly different from JDK's one in that its `AttachCurrentThread` first argument is of type `JNIEnv**` instead of `void**`.
