### ISSUE TITLE
Move artifacts to an other repository

### ISSUE THREAD

**Issue by olivervr** [LanderlYoung/Jenny#8]
As JFrog announced the deprecation of jcenter (see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter), please move the artifacts to an other repository.

**Comment by LanderlYoung** [comment]
> As JFrog announced the deprecation of jcenter (see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter), please move the artifacts to an other repository.

Oh,  shoot... didn't even know.
Will do latter on ...

**Comment by LanderlYoung** [comment]
It's now on maven central https://search.maven.org/artifact/io.github.landerlyoung/jenny-compiler
version 1.1.2 is on maven central now, new versions will be published to maven central.

BTW, bintray now is buggy with GitHub login, old version can't be transferred, but I don't think is a severe issue, so just ignore it.
