### ISSUE TITLE
Repeated @NativeProxyForClasses dosn't produce any output

### ISSUE THREAD

**Issue by TripleWhy** [LanderlYoung/Jenny#9]
Repro: Add multiple `@NativeProxyForClasses` annotations to a class.
Observed: Now Jenny won't produce any files.
Expected: Jenny should produce multiple files.

**Comment by LanderlYoung** [comment]
I tried, and it seems repeatable annotation can't work properly with kotlin. -> https://discuss.kotlinlang.org/t/issue-with-repeated-java-8-annotations/1667
please don't repeat them just add the `@NativeProxyForClasses` to any random element

```java
@NativeProxyForClasses
class XX {

    @NativeProxyForClasses
    private static final int SOME_CLASS = 0;

    @NativeProxyForClasses
    private static final int SOME_CLASS_2 = 0;
}
```
